name: CI
on: # Controls when the workflow will run
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
 workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  build:
   runs-on: ${{ matrix.os }}
   strategy:
    matrix:
     os: [ubuntu-latest, macos-latest]
   steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'true'
      - name: clang on ${{ matrix.os }}
        run: clang -v|head -1
      - name: build on ${{ matrix.os }}
        run:  cd k.edu && make
      - name: run on ${{ matrix.os }}
        run: echo "\\\\" >x.k && ./a x.k
