name: MacOS build
on: # Controls when the workflow will run
 push:
  branches: [ "main" ]
 workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  build:
   runs-on: macos-latest
   permissions: write-all
   steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'true'
      - name: clang
        run: clang -v
      - name: clang
        run: clang -dM -E - </dev/null
      - name: build
        run: if ! grep `cd k.edu && git rev-parse HEAD` mac; then cd k.edu && make; fi
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         if ! grep `cd k.edu && git rev-parse HEAD` mac; then
          gh release create mac-latest --repo="$GITHUB_REPOSITORY" --title=mac-latest k.edu/a
         fi
      - name: mac add
        run: |
         if ! grep `cd k.edu && git rev-parse HEAD` mac; then 
          (cd k.edu && git rev-parse HEAD>>../mac)
          git config --global user.name 'github-action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git add mac; git commit -m "$(date -u)"; git push
         fi
