name: MacOS build
on: # Controls when the workflow will run
 push:
  branches: [ "main" ]
 workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  build:
   runs-on: macos-latest
   permissions: write-all
   steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'true'
      - name: clang
        run: clang -v
      - name: clang
        run: clang -dM -E - </dev/null
      - name: build
        run: cd k.edu && make
